export enum AucctusQueryKeys {
  /* --- Auth --- */
  userDetails = 'userDetails',
  allUsers = 'allusers',
  dashboard = 'dashboard',

  conceptIgnitionQuestionnaire = 'conceptIgnitionQuestionnaire',
  /* Concepts */
  concepts = 'concepts',
  concept = 'concept',
  conceptVersions = 'conceptVersions',
  conceptSeed = 'conceptSeed',
  conceptSeedDraft = 'conceptSeedDraft',
  conceptSeedDraftAnswers = 'conceptSeedDraftAnswers',
  seeds = 'seeds',
  conceptOverview = 'overview',
  customerProfiles = 'customerProfiles',
  customerProfile = 'customerProfile',
  customerProfileJobs = 'customerProfileJobs',
  customerJob = 'customerJob',
  customerPain = 'customerPain',
  customerJourneyStep = 'customerJourneyStep',
  financialProjection = 'financialProjection',
  marketScan = 'marketScan',
  assumption = 'assumption',
  assumptions = 'assumptions',
  assumptionTestDetails = 'assumptionTestDetails',
  conceptTestDetails = 'conceptTestDetails',
  assumptionTestStatusOverview = 'assumptionTestStatusOverview',
  incumbent = 'incumbent',
  startup = 'startup',
  customerProfileConversation = 'customerProfileConversation',
  customerProfileConversationSearch = 'customerProfileConversationSearch',
  customerProfileRealWorldSignals = 'customerProfileRealWorldSignals',
  customerProfileRealWorldSignal = 'customerProfileRealWorldSignal',

  /* External APIs */
  clearbitCompany = 'clearbitCompany',
  articlePublishedDate = 'articlePublishedDate',
}
