export enum AucctusQueryKeys {
  /* --- Auth --- */
  userDetails = 'userDetails',
  allUsers = 'allusers',
  dashboard = 'dashboard',

  conceptIgnitionQuestionnaire = 'conceptIgnitionQuestionnaire',
  /* Concepts */
  concepts = 'concepts',
  concept = 'concept',
  conceptVersions = 'conceptVersions',
  conceptSeed = 'conceptSeed',
  conceptSeedDraft = 'conceptSeedDraft',
  conceptSeedDraftAnswers = 'conceptSeedDraftAnswers',
  seeds = 'seeds',
  customerProfiles = 'customerProfiles',
  customerProfile = 'customerProfile',
  customerProfileJobs = 'customerProfileJobs',
  customerJob = 'customerJob',
  customerPain = 'customerPain',
  customerJourneyStep = 'customerJourneyStep',
  financialProjection = 'financialProjection',
  marketScan = 'marketScan',
  assumption = 'assumption',
  assumptions = 'assumptions',
  assumptionTestDetails = 'assumptionTestDetails',
  conceptTestDetails = 'conceptTestDetails',
  assumptionTestStatusOverview = 'assumptionTestStatusOverview',
  incumbent = 'incumbent',
  startup = 'startup',
  customerProfileConversation = 'customerProfileConversation',
  customerProfileConversationSearch = 'customerProfileConversationSearch',
  customerProfileRealWorldSignals = 'customerProfileRealWorldSignals',
  customerProfileRealWorldSignal = 'customerProfileRealWorldSignal',
  /* Testing */
  testDetails = 'testDetails',
  testDetail = 'testDetail',
  testCollateral = 'testCollateral',
  testParticipants = 'testParticipants',
  testResults = 'testResults',
  testAssumptions = 'testAssumptions',
  /* Financial Projection V2 */
  financialProjectionV2 = 'financialProjectionV2',
  pricingV2 = 'pricingV2',
  businessModelV2 = 'businessModelV2',
  marketSizingV2 = 'marketSizingV2',
  marketSizingAssumptionV2 = 'marketSizingAssumptionV2',
  costDriverV2 = 'costDriverV2',
  distributionChannelV2 = 'distributionChannelV2',

  /* External APIs */
  clearbitCompany = 'clearbitCompany',
  articlePublishedDate = 'articlePublishedDate',
}
