/**
 * React Query hooks for Scoring Configuration
 *
 * Provides hooks for fetching and mutating scoring configuration data
 * used in portfolio prioritization.
 */

import { useMutation, useQuery, useQueryClient } from 'react-query';
import { toast } from '@components';
import api from '@libs/api';
import {
  IScoringCategoryCreate,
  IScoringConfig,
  IScoringConfigSave,
  IScoringConfigSaveResponse,
} from '@libs/api/types';
import utils from '@libs/utils';
import { AucctusQueryKeys } from './query-keys';

/**
 * Hook to fetch scoring configuration for an account
 */
export const useScoringConfig = (accountUuid: string | undefined) => {
  const query = useQuery({
    queryKey: [AucctusQueryKeys.scoringConfig, accountUuid],
    queryFn: async () => {
      if (!accountUuid) return null;
      return await api.account.getScoringConfig(accountUuid);
    },
    enabled: !!accountUuid,
    staleTime: 1000 * 60 * 5, // 5 minutes
  });

  return {
    ...query,
    config: query.data as IScoringConfig | null,
    categories: query.data?.categories ?? [],
    totalQuestions: query.data?.totalQuestions ?? 0,
    currentVersion: query.data?.currentVersion ?? null,
  };
};

/**
 * Hook to save scoring configuration
 */
export const useSaveScoringConfig = (accountUuid: string | undefined) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: IScoringConfigSave) => {
      if (!accountUuid) throw new Error('Account UUID is required');
      return await api.account.saveScoringConfig(accountUuid, data);
    },
    onSuccess: (response: IScoringConfigSaveResponse) => {
      queryClient.invalidateQueries({
        queryKey: [AucctusQueryKeys.scoringConfig, accountUuid],
      });

      if (response.rescoreTaskId) {
        toast.success(
          'Scoring configuration saved. Re-scoring concepts in background...',
        );
      } else {
        toast.success('Scoring configuration saved successfully');
      }
    },
    onError: (error: unknown) => {
      const message = utils.osiris.parseFormError(error);
      toast.error(message || 'Failed to save scoring configuration');
    },
  });
};

/**
 * Hook to create a new scoring category
 */
export const useCreateScoringCategory = (accountUuid: string | undefined) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: IScoringCategoryCreate) => {
      if (!accountUuid) throw new Error('Account UUID is required');
      return await api.account.createScoringCategory(accountUuid, data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [AucctusQueryKeys.scoringConfig, accountUuid],
      });
      toast.success('Category created successfully');
    },
    onError: (error: unknown) => {
      const message = utils.osiris.parseFormError(error);
      toast.error(message || 'Failed to create category');
    },
  });
};

/**
 * Hook to delete a scoring category
 */
export const useDeleteScoringCategory = (accountUuid: string | undefined) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (categoryUuid: string) => {
      if (!accountUuid) throw new Error('Account UUID is required');
      return await api.account.deleteScoringCategory(accountUuid, categoryUuid);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [AucctusQueryKeys.scoringConfig, accountUuid],
      });
      toast.success('Category deleted');
    },
    onError: (error: unknown) => {
      const message = utils.osiris.parseFormError(error);
      toast.error(message || 'Failed to delete category');
    },
  });
};

/**
 * Hook to check if scoring config exists.
 *
 * Note: This hook no longer auto-initializes with defaults. Scoring criteria
 * are now generated dynamically by AI when Nucleus processing completes.
 * For existing accounts, admins can trigger generation via Django admin.
 *
 * @deprecated The auto-init behavior has been removed. This hook now only
 * returns the initialization state for backwards compatibility.
 */
export const useAutoInitScoringConfig = (accountUuid: string | undefined) => {
  const { categories, isLoading } = useScoringConfig(accountUuid);

  return {
    isInitializing: isLoading,
    isInitialized: categories.length > 0,
    // Scoring criteria are generated by Nucleus completion, not auto-initialized
    needsGeneration: !isLoading && categories.length === 0,
  };
};
