/**
 * Agent-Side TSX to JS Compiler
 *
 * This module compiles React TSX components generated by the agent into
 * browser-executable JavaScript with scope injection for runtime dependency resolution.
 *
 * The compiled output expects these scope variables to be provided at runtime:
 * - React: The React library
 * - Components: All exports from @components
 * - Utils: All exports from @libs/utils/react
 * - Recharts: All exports from recharts
 *
 * @example
 * ```typescript
 * import { compileComponent, compileComponentFromFile } from './compile';
 *
 * // From string
 * const jsCode = await compileComponent(tsxSourceCode);
 *
 * // From file
 * const jsCode = await compileComponentFromFile('./MyComponent.tsx');
 * ```
 */

import * as esbuild from 'esbuild';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Mapping of import paths to scope variable names
 * These will be injected at runtime by the frontend
 */
const SCOPE_MAPPINGS: Record<string, string> = {
  react: 'React',
  recharts: 'Recharts',
  'react-markdown': 'Components', // ReactMarkdown is exposed via Components.ReactMarkdown
  '@components': 'Components',
  '@libs/utils/react': 'Utils',
  'lucide-react': 'LucideIcons', // All Lucide icons
  'framer-motion': 'FramerMotion', // All Framer Motion exports
  // @radix-ui/* packages are handled dynamically via RadixUI namespace
};

/**
 * Additional named imports that need special handling
 * Maps specific named imports to their scope path
 */
const NAMED_IMPORT_MAPPINGS: Record<string, { scope: string; path: string }> = {
  cn: { scope: 'Utils', path: 'cn' },
  Icon: { scope: 'Components', path: 'Icon' },
  toast: { scope: 'Components', path: 'toast' },
};

/**
 * esbuild plugin that intercepts external imports and replaces them
 * with references to scope variables that will be injected at runtime.
 */
const scopeInjectionPlugin: esbuild.Plugin = {
  name: 'scope-injection',
  setup(build) {
    // Intercept all imports that should come from scope
    const externalPattern =
      /^(react|recharts|react-markdown|lucide-react|framer-motion|@radix-ui|@components|@libs)/;

    build.onResolve({ filter: externalPattern }, (args) => {
      return {
        path: args.path,
        namespace: 'scope-inject',
      };
    });

    build.onLoad({ filter: /.*/, namespace: 'scope-inject' }, (args) => {
      // Determine which scope variable to use
      let scopeVar = 'Components'; // Default fallback

      if (args.path === 'react') {
        scopeVar = 'React';
      } else if (args.path === 'react-markdown') {
        // react-markdown is available via Components.ReactMarkdown
        return {
          contents: `module.exports = { default: Components.ReactMarkdown };`,
          loader: 'js',
        };
      } else if (args.path.startsWith('@radix-ui/react-')) {
        // Handle all @radix-ui/react-* packages dynamically
        // Extract component name: @radix-ui/react-dialog -> Dialog
        const packageName = args.path.replace('@radix-ui/react-', '');
        // Convert kebab-case to PascalCase: alert-dialog -> AlertDialog
        const componentName = packageName
          .split('-')
          .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
          .join('');
        return {
          contents: `module.exports = RadixUI.${componentName};`,
          loader: 'js',
        };
      } else if (args.path === 'lucide-react') {
        // Lucide icons are available as a separate scope variable
        return {
          contents: `module.exports = LucideIcons;`,
          loader: 'js',
        };
      } else if (args.path === 'framer-motion') {
        // Framer Motion is available as a separate scope variable
        return {
          contents: `module.exports = FramerMotion;`,
          loader: 'js',
        };
      } else if (args.path === 'recharts') {
        scopeVar = 'Recharts';
      } else if (
        args.path === '@components' ||
        args.path.startsWith('@components/')
      ) {
        scopeVar = 'Components';
      } else if (
        args.path === '@libs/utils/react' ||
        args.path.startsWith('@libs/')
      ) {
        scopeVar = 'Utils';
      }

      // Export the scope variable as the module
      return {
        contents: `module.exports = ${scopeVar};`,
        loader: 'js',
      };
    });
  },
};

/**
 * Configuration options for the compiler
 */
export interface CompilerOptions {
  /**
   * Whether to minify the output
   * @default false
   */
  minify?: boolean;

  /**
   * Whether to generate source maps
   * @default false
   */
  sourcemap?: boolean;

  /**
   * Additional esbuild options
   */
  esbuildOptions?: Partial<esbuild.BuildOptions>;
}

/**
 * Result of compilation
 */
export interface CompilationResult {
  /**
   * The compiled JavaScript code
   */
  code: string;

  /**
   * Source map if generated
   */
  sourceMap?: string;

  /**
   * Any warnings from the compilation
   */
  warnings: string[];

  /**
   * Metadata about the compilation
   */
  metadata: {
    /**
     * Original size in bytes
     */
    originalSize: number;

    /**
     * Compiled size in bytes
     */
    compiledSize: number;

    /**
     * Time taken to compile in milliseconds
     */
    compileTime: number;
  };
}

/**
 * Wraps the compiled code in a factory function that receives scope variables
 * and returns the default export (the component).
 *
 * The wrapper:
 * 1. Receives React, Components, Utils, Recharts, LucideIcons, RadixUI, FramerMotion as arguments
 * 2. Executes the compiled IIFE
 * 3. Returns the default export (the React component)
 *
 * IMPORTANT: Keep this in sync with:
 * - scripts/compile-test.mjs (wrapWithScopeInjection function)
 * - src/app/components/DynamicComponent/scopeRegistry.ts (Components and Utils exports)
 */
function wrapWithScopeInjection(
  compiledCode: string,
  globalName: string,
): string {
  return `
// Agent-compiled component
// This code expects scope injection at runtime
(function(React, Components, Utils, Recharts, LucideIcons, RadixUI, FramerMotion) {
  "use strict";
  
  // ===== REACT =====
  // Hooks
  var useState = React.useState;
  var useEffect = React.useEffect;
  var useMemo = React.useMemo;
  var useCallback = React.useCallback;
  var useRef = React.useRef;
  var useContext = React.useContext;
  var useReducer = React.useReducer;
  var useLayoutEffect = React.useLayoutEffect;
  var useImperativeHandle = React.useImperativeHandle;
  var useDebugValue = React.useDebugValue;
  var useDeferredValue = React.useDeferredValue;
  var useTransition = React.useTransition;
  var useId = React.useId;
  var useSyncExternalStore = React.useSyncExternalStore;
  var useInsertionEffect = React.useInsertionEffect;
  
  // Component utilities
  var Fragment = React.Fragment;
  var Suspense = React.Suspense;
  var lazy = React.lazy;
  var memo = React.memo;
  var forwardRef = React.forwardRef;
  var createContext = React.createContext;
  var createElement = React.createElement;
  
  // ===== UTILS =====
  // Class name merging
  var cn = Utils.cn;
  
  // Number formatting
  var formatLargeNumber = Utils.formatLargeNumber;
  var formatNumber = Utils.formatNumber;
  var calculatePercent = Utils.calculatePercent;
  var clamp = Utils.clamp;
  
  // String formatting
  var toTitleCase = Utils.toTitleCase;
  var capitalize = Utils.capitalize;
  var pluralize = Utils.pluralize;
  var camelCaseToTitleCase = Utils.camelCaseToTitleCase;
  var snakeToTitleCase = Utils.snakeToTitleCase;
  
  // Date/Time formatting
  var dateFormatter = Utils.dateFormatter;
  var formatDate = Utils.formatDate;
  var formatDateFromTimestamp = Utils.formatDateFromTimestamp;
  
  // ===== COMPONENTS =====
  // Core UI
  var Icon = Components.Icon;
  var Button = Components.Button;
  var Modal = Components.Modal;
  var Loading = Components.Loading;
  var AucctusProgress = Components.Progress;
  var AucctusTooltip = Components.Tooltip;
  var ComponentTooltip = Components.ComponentTooltip;
  var toast = Components.toast;
  
  // Form elements
  var Input = Components.Input;
  var AucctusSelect = Components.Select;
  var ToggleSwitch = Components.ToggleSwitch;
  
  // Layout
  var Container = Components.Container;
  var Portal = Components.Portal;
  var AucctusAvatar = Components.Avatar;
  var Banner = Components.Banner;
  var Header = Components.Header;
  
  // Tabs (Aucctus components - use AucctusTabs to avoid conflict with Radix Tabs)
  var AucctusTabs = Components.Tabs;
  var AucctusTabsList = Components.TabsList;
  var AucctusTabsTrigger = Components.TabsTrigger;
  var AucctusTabsContent = Components.TabsContent;
  
  // Table
  var Table = Components.Table;
  
  // Badge - default simple badge component
  // Usage: <Badge value="Label" /> or <Badge value={5} />
  var Badge = Components.Badge;
  // Full badge namespace for specialized badges
  var BadgeAll = Components.BadgeAll;
  
  // Card - default detail card component
  var Card = Components.Card;
  // Full card namespace for specialized cards
  var CardAll = Components.CardAll;
  
  // Other components
  var ComponentCarousel = Components.ComponentCarousel;
  var FileDropzone = Components.FileDropzone;
  
  // Markdown rendering
  // Usage: <ReactMarkdown>{markdownContent}</ReactMarkdown>
  var ReactMarkdown = Components.ReactMarkdown;
  
  // ===== RADIX UI PRIMITIVES =====
  // These are headless, unstyled components - you must style them yourself
  var Popover = Components.Popover;
  var Collapsible = Components.Collapsible;
  var ScrollArea = Components.ScrollArea;
  var RadioGroup = Components.RadioGroup;
  var RadixSelect = Components.RadixSelect;
  
  // ===== RECHARTS =====
  // Container
  var ResponsiveContainer = Recharts.ResponsiveContainer;
  
  // Chart types
  var LineChart = Recharts.LineChart;
  var BarChart = Recharts.BarChart;
  var PieChart = Recharts.PieChart;
  var AreaChart = Recharts.AreaChart;
  var ScatterChart = Recharts.ScatterChart;
  var RadarChart = Recharts.RadarChart;
  var RadialBarChart = Recharts.RadialBarChart;
  var ComposedChart = Recharts.ComposedChart;
  var Treemap = Recharts.Treemap;
  var Sankey = Recharts.Sankey;
  var FunnelChart = Recharts.FunnelChart;
  
  // Chart elements
  var Line = Recharts.Line;
  var Bar = Recharts.Bar;
  var Pie = Recharts.Pie;
  var Area = Recharts.Area;
  var Scatter = Recharts.Scatter;
  var Radar = Recharts.Radar;
  var RadialBar = Recharts.RadialBar;
  var Funnel = Recharts.Funnel;
  var Cell = Recharts.Cell;
  
  // Axes
  var XAxis = Recharts.XAxis;
  var YAxis = Recharts.YAxis;
  var ZAxis = Recharts.ZAxis;
  var PolarGrid = Recharts.PolarGrid;
  var PolarAngleAxis = Recharts.PolarAngleAxis;
  var PolarRadiusAxis = Recharts.PolarRadiusAxis;
  
  // Decorations
  var CartesianGrid = Recharts.CartesianGrid;
  var RechartsTooltip = Recharts.Tooltip;
  var RechartsLegend = Recharts.Legend;
  var ReferenceLine = Recharts.ReferenceLine;
  var ReferenceArea = Recharts.ReferenceArea;
  var ReferenceDot = Recharts.ReferenceDot;
  var Brush = Recharts.Brush;
  var LabelList = Recharts.LabelList;
  
  // ===== LUCIDE ICONS =====
  // All 1000+ Lucide icons are available via LucideIcons namespace
  // Import like: import { Check, X, ChevronDown } from 'lucide-react'
  // The compiled code automatically destructures from LucideIcons
  // No need to manually extract - esbuild handles destructuring
  
  // ===== RADIX UI =====
  // All Radix UI primitives are available via RadixUI namespace
  // Import like: import * as Dialog from '@radix-ui/react-dialog'
  // Maps to RadixUI.Dialog, RadixUI.Popover, etc.
  // The compiled code automatically maps @radix-ui/react-* to RadixUI.*
  
  // ===== FRAMER MOTION =====
  // All Framer Motion exports are available via FramerMotion namespace
  // Import like: import { motion, AnimatePresence } from 'framer-motion'
  // The compiled code automatically destructures from FramerMotion
  
  ${compiledCode}
  
  // Return the default export
  return ${globalName}.default || ${globalName};
})
`.trim();
}

/**
 * Compiles a TSX component string to browser-executable JavaScript.
 *
 * @param tsxCode - The raw TSX source code
 * @param options - Compilation options
 * @returns The compiled JavaScript code ready for browser execution
 *
 * @example
 * ```typescript
 * const tsxCode = `
 *   import React from 'react';
 *   import { Icon } from '@components';
 *
 *   const MyComponent: React.FC = () => {
 *     return <Icon variant="check" />;
 *   };
 *
 *   export default MyComponent;
 * `;
 *
 * const result = await compileComponent(tsxCode);
 * // result.code can now be executed in the browser with scope injection
 * ```
 */
export async function compileComponent(
  tsxCode: string,
  options: CompilerOptions = {},
): Promise<CompilationResult> {
  const startTime = Date.now();
  const originalSize = Buffer.byteLength(tsxCode, 'utf8');
  const globalName = '__AgentComponent__';

  try {
    const result = await esbuild.build({
      stdin: {
        contents: tsxCode,
        loader: 'tsx',
        resolveDir: process.cwd(),
        sourcefile: 'component.tsx',
      },
      bundle: true,
      format: 'iife',
      globalName,
      platform: 'browser',
      target: ['es2020'],
      minify: options.minify ?? false,
      sourcemap: options.sourcemap ? 'external' : false,
      plugins: [scopeInjectionPlugin],
      write: false,
      logLevel: 'warning',
      ...options.esbuildOptions,
    });

    if (!result.outputFiles || result.outputFiles.length === 0) {
      throw new Error('Compilation produced no output');
    }

    const compiledCode = result.outputFiles[0].text;
    const wrappedCode = wrapWithScopeInjection(compiledCode, globalName);

    const warnings = result.warnings.map((w) => {
      return `${w.location?.file ?? 'unknown'}:${w.location?.line ?? 0}: ${w.text}`;
    });

    return {
      code: wrappedCode,
      sourceMap: result.outputFiles[1]?.text,
      warnings,
      metadata: {
        originalSize,
        compiledSize: Buffer.byteLength(wrappedCode, 'utf8'),
        compileTime: Date.now() - startTime,
      },
    };
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Compilation failed: ${error.message}`);
    }
    throw error;
  }
}

/**
 * Compiles a TSX component from a file path.
 *
 * @param filePath - Path to the TSX file
 * @param options - Compilation options
 * @returns The compiled JavaScript code ready for browser execution
 */
export async function compileComponentFromFile(
  filePath: string,
  options: CompilerOptions = {},
): Promise<CompilationResult> {
  const absolutePath = path.resolve(filePath);

  if (!fs.existsSync(absolutePath)) {
    throw new Error(`File not found: ${absolutePath}`);
  }

  const tsxCode = fs.readFileSync(absolutePath, 'utf8');
  return compileComponent(tsxCode, options);
}

/**
 * Validates that a compiled component can be instantiated.
 * This is a basic syntax check - it doesn't guarantee the component works.
 *
 * @param compiledCode - The compiled JavaScript code
 * @returns True if the code appears valid
 */
export function validateCompiledCode(compiledCode: string): boolean {
  try {
    // Basic syntax check - try to create a function from the code
    // This doesn't execute it, just checks syntax
    new Function(
      'React',
      'Components',
      'Utils',
      'Recharts',
      'LucideIcons',
      'RadixUI',
      'FramerMotion',
      `return ${compiledCode}`,
    );
    return true;
  } catch {
    return false;
  }
}

/**
 * Extracts metadata from a TSX source file without full compilation.
 * Useful for quick analysis of component structure.
 *
 * @param tsxCode - The raw TSX source code
 * @returns Metadata about the component
 */
export function analyzeComponent(tsxCode: string): {
  hasDefaultExport: boolean;
  imports: string[];
  estimatedComplexity: 'low' | 'medium' | 'high';
} {
  const hasDefaultExport =
    /export\s+default\s+/.test(tsxCode) ||
    /export\s*\{\s*.*as\s+default\s*\}/.test(tsxCode);

  const importMatches =
    tsxCode.match(/import\s+.*?from\s+['"]([^'"]+)['"]/g) || [];
  const imports = importMatches.map((match) => {
    const fromMatch = match.match(/from\s+['"]([^'"]+)['"]/);
    return fromMatch ? fromMatch[1] : '';
  });

  // Estimate complexity based on file size and patterns
  const lineCount = tsxCode.split('\n').length;
  const hasCharts = imports.some((i) => i.includes('recharts'));
  const hasMultipleComponents =
    (tsxCode.match(/const\s+\w+:\s*React\.FC/g) || []).length > 1;

  let complexity: 'low' | 'medium' | 'high' = 'low';
  if (lineCount > 500 || (hasCharts && hasMultipleComponents)) {
    complexity = 'high';
  } else if (lineCount > 200 || hasCharts || hasMultipleComponents) {
    complexity = 'medium';
  }

  return {
    hasDefaultExport,
    imports,
    estimatedComplexity: complexity,
  };
}

// Export types for external use
export type { esbuild };
