import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  BarChart3,
  Beaker,
  Bell,
  BookOpen,
  Box,
  Briefcase,
  Building,
  Building2,
  Calendar,
  ChartColumn,
  Check,
  CheckCircle2,
  ChefHat,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleDot,
  Clipboard,
  ClipboardList,
  ClipboardPen,
  Clock,
  ClockArrowDown,
  ClockArrowUp,
  Columns3,
  Compass,
  Cpu,
  Database,
  DollarSign,
  Download,
  DownloadCloud,
  Droplets,
  EllipsisVertical,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCode,
  FilePlus,
  FileSearch,
  FileText,
  FileUp,
  Ghost,
  GitMerge,
  Globe,
  Handshake,
  Heart,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Key,
  Landmark,
  LayoutDashboard,
  Layers,
  Leaf,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Link,
  Link2,
  Linkedin,
  List,
  ListChecks,
  ListFilter,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  Minus,
  MonitorPlay,
  Palette,
  Pencil,
  PieChart,
  PiggyBank,
  Play,
  PlaySquare,
  Plus,
  PresentationIcon,
  Radar,
  Radio,
  RefreshCw,
  Repeat2,
  Rocket,
  Route,
  Save,
  Scale,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  SwitchCamera,
  Swords,
  Target,
  Telescope,
  Thermometer,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Umbrella,
  Upload,
  User,
  UserPen,
  Users,
  UserSquare,
  Wand2,
  Waves,
  Workflow,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import React from 'react';

export type AgentDecidedColor =
  | 'primary'
  | 'secondary'
  | 'brand'
  | 'error'
  | 'warning'
  | 'success'
  | 'info'
  | 'disabled';

export const colorToStrokeClass: Record<AgentDecidedColor, string> = {
  primary: 'aucctus-stroke-primary',
  secondary: 'aucctus-stroke-secondary',
  brand: 'aucctus-stroke-brand-primary',
  error: 'aucctus-stroke-error-primary',
  warning: 'aucctus-stroke-warning-primary',
  success: 'aucctus-stroke-success-primary',
  info: 'aucctus-stroke-info-primary',
  disabled: 'aucctus-stroke-disabled',
};

export const ICON_MAP: Record<string, LucideIcon> = {
  activity: Activity,
  'ai-conclusion': Sparkles,
  alert: TriangleAlert,
  'alert-circle': AlertCircle,
  'alert-exclamation': CircleAlert,
  'alert-octagon': AlertOctagon,
  'alert-triangle': AlertTriangle,
  award: Award,
  'align-right-01': AlignRight,
  'annotation-dots': MessageSquare,
  announcement: Bell,
  arrowdown: ArrowDown,
  arrowleft: ArrowLeft,
  arrowright: ArrowRight,
  arrowup: ArrowUp,
  arrowupright: ArrowUpRight,
  bank: Landmark,
  'bar-chart-3': BarChart3,
  barchart: BarChart3,
  beaker: Beaker,
  board: Columns3,
  'book-open': BookOpen,
  briefcase: Briefcase,
  building: Building,
  'building-2': Building2,
  'building-02': Building2,
  'building-03': Building,
  calendar: Calendar,
  'chart-column': ChartColumn,
  check: Check,
  'check-circle-2': CheckCircle2,
  'check-circle-broken': CheckCircle2,
  'chef-hat': ChefHat,
  'chevron-right': ChevronRight,
  chevrondown: ChevronDown,
  chevronleft: ChevronLeft,
  chevronright: ChevronRight,
  chevronup: ChevronUp,
  circle: Circle,
  'circle-empty': CircleDot,
  clipboard: Clipboard,
  'clipboard-list': ClipboardList,
  clock: Clock,
  'clock-fast-forward': ClockArrowUp,
  'clock-rewind': ClockArrowDown,
  'clock-stopwatch': Timer,
  closeX: X,
  columns: Columns3,
  compass: Compass,
  'compass-03': Compass,
  cube: Box,
  'currency-dollar': DollarSign,
  database: Database,
  currencydollar: DollarSign,
  'dataflow-04': Workflow,
  decreasing: TrendingDown,
  'dollar-sign': DollarSign,
  'dots-vertical': EllipsisVertical,
  download: Download,
  'download-cloud': DownloadCloud,
  droplets: Droplets,
  economic: DollarSign,
  edit: Pencil,
  environmental: Leaf,
  'expand-06': Expand,
  eye: Eye,
  'eye-off': EyeOff,
  file: File,
  'file-2': File,
  'file-attachment': FileUp,
  'file-open': File,
  'file-plus': FilePlus,
  'file-search': FileSearch,
  'file-text': FileText,
  filecode: FileCode,
  'filter-lines': ListFilter,
  future: Telescope,
  gear: Settings,
  'settings-01': SlidersHorizontal,
  ghost: Ghost,
  'git-merge': GitMerge,
  globe: Globe,
  handshake: Handshake,
  heart: Heart,
  help: HelpCircle,
  'help-circle': HelpCircle,
  home: Home,
  image: Image,
  'inbox-02': Inbox,
  increasing: TrendingUp,
  key: Key,
  'layout-dashboard': LayoutDashboard,
  layers: Layers,
  legal: Scale,
  lifebuoy: LifeBuoy,
  lightbulb: Lightbulb,
  'line-chart-up': LineChart,
  'line-chart-up-02': LineChart,
  link: Link,
  'link-01': Link,
  'link-03': Link,
  'link-external': ExternalLink,
  'link-source': Link2,
  linkedin: Linkedin,
  list: List,
  'loading-02': Loader2,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  map: Map,
  'map-01': Map,
  'map-02': Map,
  'map-pin': MapPin,
  'market-resonance': ThumbsUp,
  'message-circle': MessageCircle,
  minus: Minus,
  palette: Palette,
  'paper-airplane': Send,
  'pie-chart': PieChart,
  'piggy-bank': PiggyBank,
  play: Play,
  'play-square': PlaySquare,
  plus: Plus,
  political: Landmark,
  'presentation-chart': PresentationIcon,
  'product-blueprint': ClipboardPen,
  radar: Radar,
  refresh: RefreshCw,
  'refresh-cw': RefreshCw,
  'repeat-02': Repeat2,
  rocket: Rocket,
  route: Route,
  save: Save,
  'search-md': Search,
  'search-refraction': Search,
  shield: Shield,
  'shield-dollar': ShieldCheck,
  'signal-02': Radio,
  smartphone: Smartphone,
  social: Users,
  sparkles: Sparkles,
  stagnating: Minus,
  star: Star,
  'star-01': Star,
  survey: ListChecks,
  'switch-vertical-01': SwitchCamera,
  swords: Swords,
  target: Target,
  'target-round': Target,
  technological: Cpu,
  telescope: Telescope,
  'test-drive': MonitorPlay,
  thermometer: Thermometer,
  threeStars: Sparkles,
  'thumbs-up': ThumbsUp,
  trash: Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  trendup: TrendingUp,
  umbrella: Umbrella,
  upload: Upload,
  user: User,
  'user-group': Users,
  users: Users,
  'user-square': UserSquare,
  'users-02': Users,
  'users-03': Users,
  'users-edit': UserPen,
  warning: TriangleAlert,
  waves: Waves,
  'wizard-of-oz': Wand2,
  zap: Zap,
};

export function resolveIcon(variant: string): LucideIcon {
  return ICON_MAP[variant] ?? HelpCircle;
}

/**
 * Drop-in replacement for the old <Icon variant={dynamicString} /> pattern.
 * Use direct lucide imports for static icons; use DynamicIcon only when
 * the variant is determined at runtime.
 */
export const DynamicIcon: React.FC<
  { variant: string } & Omit<React.SVGProps<SVGSVGElement>, 'ref'> & {
      size?: number | string;
    }
> = ({ variant, ...props }) => {
  const IconComp = resolveIcon(variant);
  return <IconComp {...props} />;
};
