"""Query planning layer — interpretation, reconnaissance, provider-specific query generation.

Sits between user input and provider calls. Replaces raw query passthrough with:
1. LLM-assisted query interpretation (gpt-4o-mini, ~$0.001)
2. Lightweight reconnaissance pass (1 Tavily search, 1 credit)
3. Provider-specific query adapters
4. Local evidence check before external retrieval

No hardcoded market dictionaries. Uses general heuristics + LLM for interpretation.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

from pydantic import BaseModel

from app.config import (
    GDELT_ENABLED, GDELT_QUERIES_PER_AGENT,
    LOCAL_EVIDENCE_SUFFICIENCY,
    RECON_MAX_RESULTS, RECON_TAVILY_SEARCHES,
    SEC_EDGAR_ENABLED, SEC_EDGAR_QUERIES_PER_AGENT,
    TAVILY_QUERIES_PER_AGENT,
    USPTO_ENABLED, USPTO_QUERIES_PER_AGENT,
    use_real_apis,
)
from app.services import llm

logger = logging.getLogger(__name__)


# ── Query plan data structures ──

@dataclass
class ProviderQueries:
    """Provider-specific queries generated by the planner."""
    tavily: list[str] = field(default_factory=list)
    gdelt: list[str] = field(default_factory=list)
    sec_edgar: list[str] = field(default_factory=list)
    uspto: list[str] = field(default_factory=list)


@dataclass
class QueryPlan:
    """Structured query plan produced by the planner.

    Consumed by agents to replace hardcoded search templates.
    """
    raw_query: str
    canonical_market_term: str
    parent_category: str
    narrower_terms: list[str] = field(default_factory=list)
    adjacent_terms: list[str] = field(default_factory=list)
    synonyms: list[str] = field(default_factory=list)
    entity_candidates: list[str] = field(default_factory=list)

    # Provider recommendations (True = worth querying)
    use_gdelt: bool = True
    use_sec_edgar: bool = True
    use_uspto: bool = False

    # Market signal from reconnaissance
    market_signals: str = ""  # e.g. "public-company-heavy", "startup-heavy", "niche"

    # Per-agent planned queries
    incumbents_queries: ProviderQueries = field(default_factory=ProviderQueries)
    emerging_queries: ProviderQueries = field(default_factory=ProviderQueries)
    market_sizing_queries: ProviderQueries = field(default_factory=ProviderQueries)

    # Local evidence summary
    local_evidence_count: int = 0
    local_evidence_sufficient: bool = False

    # Planner confidence
    interpretation_confidence: str = "medium"  # high, medium, low
    notes: str = ""


# ── LLM schema for query interpretation ──

class QueryInterpretation(BaseModel):
    canonical_market_term: str
    parent_category: str
    narrower_terms: list[str]
    adjacent_terms: list[str]
    synonyms: list[str]
    likely_public_companies: list[str]
    likely_startups: list[str]
    is_patent_relevant: bool
    is_news_heavy: bool
    is_niche: bool
    confidence: str  # high, medium, low
    notes: str


# ── Main planner entry point ──

async def build_query_plan(
    market_space: str,
    company_name: str,
    company_context: str | None = None,
    strategy_lens: dict | None = None,
    evaluation_posture: str = "established_company",
    framing_question: str | None = None,
) -> QueryPlan:
    """Build a structured query plan from user input.

    Steps:
    1. LLM-assisted query interpretation (gpt-4o-mini)
    2. Reconnaissance pass (1 Tavily search)
    3. Local evidence check
    4. Provider-specific query generation
    """
    plan = QueryPlan(raw_query=market_space, canonical_market_term=market_space,
                     parent_category=market_space)

    # Step 1: LLM query interpretation
    interpretation = await _interpret_query(market_space, company_name,
                                            company_context, framing_question)
    if interpretation:
        plan.canonical_market_term = interpretation.canonical_market_term
        plan.parent_category = interpretation.parent_category
        plan.narrower_terms = interpretation.narrower_terms[:5]
        plan.adjacent_terms = interpretation.adjacent_terms[:3]
        plan.synonyms = interpretation.synonyms[:5]
        plan.entity_candidates = (
            interpretation.likely_public_companies[:5]
            + interpretation.likely_startups[:5]
        )
        plan.use_uspto = interpretation.is_patent_relevant and USPTO_ENABLED
        plan.use_sec_edgar = (
            bool(interpretation.likely_public_companies) and SEC_EDGAR_ENABLED
        )
        plan.use_gdelt = interpretation.is_news_heavy and GDELT_ENABLED
        plan.interpretation_confidence = interpretation.confidence
        plan.notes = interpretation.notes

        # Determine market signals
        signals = []
        if interpretation.likely_public_companies:
            signals.append("public-company-heavy")
        if interpretation.likely_startups:
            signals.append("startup-active")
        if interpretation.is_patent_relevant:
            signals.append("patent-relevant")
        if interpretation.is_news_heavy:
            signals.append("news-heavy")
        if interpretation.is_niche:
            signals.append("niche")
        plan.market_signals = ", ".join(signals) if signals else "general"

    # Step 2: Reconnaissance pass
    recon_entities = await _run_reconnaissance(plan)
    if recon_entities:
        # Merge recon-discovered entities into plan (dedup)
        existing = set(e.lower() for e in plan.entity_candidates)
        for ent in recon_entities:
            if ent.lower() not in existing:
                plan.entity_candidates.append(ent)
                existing.add(ent.lower())
        plan.entity_candidates = plan.entity_candidates[:10]

    # Step 3: Local evidence check
    plan.local_evidence_count = await _check_local_evidence(market_space)
    plan.local_evidence_sufficient = (
        plan.local_evidence_count >= LOCAL_EVIDENCE_SUFFICIENCY
    )

    # Step 4: Generate provider-specific queries
    plan.incumbents_queries = _build_incumbents_queries(plan, company_name)
    plan.emerging_queries = _build_emerging_queries(plan, company_name)
    plan.market_sizing_queries = _build_market_sizing_queries(plan, company_name)

    logger.info(
        f"Query plan built: canonical='{plan.canonical_market_term}', "
        f"entities={len(plan.entity_candidates)}, "
        f"signals={plan.market_signals}, "
        f"local_evidence={plan.local_evidence_count}, "
        f"providers=[tavily"
        f"{', gdelt' if plan.use_gdelt else ''}"
        f"{', sec_edgar' if plan.use_sec_edgar else ''}"
        f"{', uspto' if plan.use_uspto else ''}]"
    )

    return plan


# ── Step 1: LLM-assisted query interpretation ──

async def _interpret_query(
    market_space: str,
    company_name: str,
    company_context: str | None,
    framing_question: str | None,
) -> QueryInterpretation | None:
    """Use gpt-4o-mini to interpret the user's market query into structured terms."""
    if not use_real_apis():
        return None

    context_snippet = ""
    if company_context:
        context_snippet = f"\nCompany context: {company_context[:300]}"
    if framing_question:
        context_snippet += f"\nFraming question: {framing_question}"

    prompt = (
        f"A user wants to research the competitive landscape for this market opportunity:\n"
        f"Market space: {market_space}\n"
        f"Company evaluating: {company_name}\n"
        f"{context_snippet}\n\n"
        f"Interpret this market query. Provide:\n"
        f"- canonical_market_term: The standard industry term for this market "
        f"(e.g., 'cloud security' not 'cloud sec solutions')\n"
        f"- parent_category: The broader industry category "
        f"(e.g., 'cybersecurity' for 'cloud security')\n"
        f"- narrower_terms: 3-5 specific sub-segments within this market\n"
        f"- adjacent_terms: 2-3 related but distinct markets\n"
        f"- synonyms: Alternate phrasings used in industry "
        f"(e.g., 'CNAPP' for 'cloud-native application protection')\n"
        f"- likely_public_companies: 3-5 public companies likely to be incumbents\n"
        f"- likely_startups: 2-3 notable startups in this space\n"
        f"- is_patent_relevant: Whether this market has significant patent activity\n"
        f"- is_news_heavy: Whether this market generates frequent news coverage\n"
        f"- is_niche: Whether this is a small/specialized market\n"
        f"- confidence: How confident you are in this interpretation (high/medium/low)\n"
        f"- notes: Any caveats about the interpretation"
    )

    try:
        result = await llm.chat_structured(
            prompt=prompt,
            response_model=QueryInterpretation,
            model="gpt-4o-mini",
            system="You are a market research expert. Interpret market queries precisely.",
            max_tokens=1024,
        )
        logger.info(
            f"Query interpretation: '{market_space}' → "
            f"canonical='{result.canonical_market_term}', "
            f"confidence={result.confidence}"
        )
        return result
    except Exception as e:
        logger.warning(f"Query interpretation failed: {e}")
        return None


# ── Step 2: Reconnaissance pass ──

async def _run_reconnaissance(plan: QueryPlan) -> list[str]:
    """Run a lightweight discovery search to find canonical market language and entities.

    Uses 1 Tavily search (1 credit) to discover real-world terminology.
    Returns discovered entity names.
    """
    if not use_real_apis() or RECON_TAVILY_SEARCHES < 1:
        return []

    from app.services import search as search_svc

    # Build a broad reconnaissance query
    recon_query = (
        f"{plan.canonical_market_term} market leaders companies "
        f"competitive landscape 2024 2025"
    )

    try:
        results = await search_svc.search(recon_query, max_results=RECON_MAX_RESULTS)
        if not results:
            return []

        # Extract entity candidates from titles and content
        entities = _extract_entities_from_results(results, plan)
        logger.info(
            f"Recon pass: {len(results)} results, "
            f"discovered entities: {entities[:5]}"
        )
        return entities
    except Exception as e:
        logger.warning(f"Reconnaissance pass failed: {e}")
        return []


def _extract_entities_from_results(
    results: list, plan: QueryPlan
) -> list[str]:
    """Extract company/entity names from search results using heuristics.

    Not LLM-based — uses simple pattern matching for speed.
    """
    import re

    # Collect text from titles and content snippets
    all_text = " ".join(
        f"{r.title} {r.content[:300]}" for r in results
    )

    # Known entity candidates from interpretation
    known = set(e.lower() for e in plan.entity_candidates)
    found: list[str] = []

    # Heuristic 1: Look for capitalized multi-word names that appear
    # near competitive keywords
    competitive_patterns = [
        r"(?:led by|including|such as|like|competitor[s]?|player[s]?|vendor[s]?|leader[s]?)"
        r"[:\s]+([A-Z][a-zA-Z]+(?:\s[A-Z][a-zA-Z]+){0,2})",
    ]
    for pattern in competitive_patterns:
        for match in re.finditer(pattern, all_text):
            name = match.group(1).strip()
            if (
                len(name) > 2
                and name.lower() not in known
                and name.lower() not in {"the", "and", "for", "its", "new"}
            ):
                found.append(name)
                known.add(name.lower())

    # Heuristic 2: Confirm existing entity candidates appear in results
    confirmed = []
    for entity in plan.entity_candidates:
        if entity.lower() in all_text.lower():
            confirmed.append(entity)

    return confirmed + found[:10]


# ── Step 3: Local evidence check ──

async def _check_local_evidence(market_space: str) -> int:
    """Check how much relevant local evidence already exists.

    Returns count of locally available relevant items.
    """
    try:
        from app.retrieval import retriever
        results = await retriever.hybrid_search(market_space, limit=LOCAL_EVIDENCE_SUFFICIENCY + 5)
        return len(results)
    except Exception as e:
        logger.warning(f"Local evidence check failed: {e}")
        return 0


# ── Step 4: Provider-specific query generation ──

def _build_incumbents_queries(plan: QueryPlan, company_name: str) -> ProviderQueries:
    """Generate provider-specific queries for the incumbents agent."""
    market = plan.canonical_market_term
    parent = plan.parent_category
    entities = plan.entity_candidates[:5]
    synonyms = plan.synonyms[:2]

    pq = ProviderQueries()

    # Tavily: natural language discovery
    pq.tavily = [
        f"{market} market leaders competitive landscape revenue market share",
        f"{market} enterprise players top companies strengths weaknesses analysis",
    ]
    # Use synonym or narrower term for the third query if available
    if synonyms:
        pq.tavily.append(
            f"{synonyms[0]} industry analysis major vendors competitive positioning"
        )
    elif plan.narrower_terms:
        pq.tavily.append(
            f"{plan.narrower_terms[0]} market leaders companies"
        )
    else:
        pq.tavily.append(
            f"{parent} industry leaders analysis 2024 2025"
        )
    pq.tavily = pq.tavily[:TAVILY_QUERIES_PER_AGENT]

    # SEC EDGAR: entity-specific queries for known public companies
    if plan.use_sec_edgar and entities:
        # Query with specific company names, not just the market term
        public_names = entities[:3]
        pq.sec_edgar = [
            f"{' OR '.join(public_names)} revenue {market}"
        ]
        pq.sec_edgar = pq.sec_edgar[:SEC_EDGAR_QUERIES_PER_AGENT]

    # GDELT: not typically used for incumbents (more for emerging/timing)

    return pq


def _build_emerging_queries(plan: QueryPlan, company_name: str) -> ProviderQueries:
    """Generate provider-specific queries for the emerging competitors agent."""
    market = plan.canonical_market_term
    synonyms = plan.synonyms[:2]

    pq = ProviderQueries()

    # Tavily: startup/funding discovery
    pq.tavily = [
        f"{market} startup funding recent series A B seed 2024 2025",
        f"{market} emerging companies startups disrupting innovative",
    ]
    if synonyms:
        pq.tavily.append(
            f"{synonyms[0]} venture capital investment funding activity"
        )
    else:
        pq.tavily.append(
            f"{market} venture capital investment trends funding rounds"
        )
    pq.tavily = pq.tavily[:TAVILY_QUERIES_PER_AGENT]

    # GDELT: recent news about startups and funding
    if plan.use_gdelt:
        pq.gdelt = [
            f"{market} startup funding investment"
        ]
        pq.gdelt = pq.gdelt[:GDELT_QUERIES_PER_AGENT]

    # USPTO: patent/innovation signals
    if plan.use_uspto:
        # Use narrower technical terms for patent search
        if plan.narrower_terms:
            patent_term = plan.narrower_terms[0]
        else:
            patent_term = market
        pq.uspto = [patent_term]
        pq.uspto = pq.uspto[:USPTO_QUERIES_PER_AGENT]

    return pq


def _build_market_sizing_queries(plan: QueryPlan, company_name: str) -> ProviderQueries:
    """Generate provider-specific queries for the market sizing agent."""
    market = plan.canonical_market_term
    parent = plan.parent_category
    synonyms = plan.synonyms[:2]

    pq = ProviderQueries()

    # Tavily: market size and forecast data
    pq.tavily = [
        f"{market} market size TAM SAM forecast CAGR 2025 2030",
        f"{market} industry report market analysis addressable market",
    ]
    if synonyms:
        pq.tavily.append(
            f"{synonyms[0]} market opportunity growth drivers constraints forecast"
        )
    elif parent != market:
        pq.tavily.append(
            f"{parent} market size growth trends forecast report"
        )
    else:
        pq.tavily.append(
            f"{market} addressable market opportunity growth drivers constraints"
        )
    pq.tavily = pq.tavily[:TAVILY_QUERIES_PER_AGENT]

    # GDELT: market trend signals
    if plan.use_gdelt:
        pq.gdelt = [
            f"{market} market growth investment trend"
        ]
        pq.gdelt = pq.gdelt[:GDELT_QUERIES_PER_AGENT]

    return pq


# ── Refinement query generation ──

def generate_refinement_queries(
    plan: QueryPlan,
    weak_dimensions: list[str],
) -> dict[str, ProviderQueries]:
    """Generate additional queries to fill coverage gaps.

    Called by coverage evaluation when evidence is insufficient.
    Returns a dict mapping agent step → additional queries.
    """
    refinements: dict[str, ProviderQueries] = {}
    market = plan.canonical_market_term
    parent = plan.parent_category

    for dim in weak_dimensions:
        pq = ProviderQueries()

        if dim == "incumbents":
            # Broaden to parent category
            pq.tavily = [f"{parent} market leaders top companies revenue"]
            if plan.adjacent_terms:
                pq.tavily.append(
                    f"{plan.adjacent_terms[0]} major vendors competitive analysis"
                )

        elif dim == "emerging":
            # Widen time window / use alternate terms
            pq.tavily = [f"{market} new entrants startups 2023 2024 2025"]
            if plan.synonyms:
                pq.gdelt = [f"{plan.synonyms[0]} startup investment"]

        elif dim == "market_sizing":
            # Broaden to parent category for sizing
            pq.tavily = [f"{parent} market size TAM forecast report"]

        elif dim == "signals":
            # More GDELT coverage
            pq.gdelt = [f"{market} industry trend development"]

        refinements[dim] = pq

    return refinements
