name: S3/CloudFront CI/CD
on:
  push:
    branches: [prod]
env:
  NODE_ENV: production
  ENVIRONMENT: production
  VITE_AUCCTUS_BASE_RESOURCE_URL: https://api.aucctus.com
  VITE_AUCCTUS_BASE_WS_URL: wss://api.aucctus.com
  VITE_SECRET_KEY: ${{ secrets.VITE_SECRET_KEY }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  # Feature flags
  FEATURE_CUSTOMER_PROFILE_CHAT: false
  FEATURE_CONCEPT_VERSIONING: true
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    environment: prod
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install --include=dev
      - name: Build
        run: npm run build
      # upload all static assets w/ cache control (dist/** is an artifact from the previous step)
      - name: Deploy assets to S3
        run: aws s3 sync ./build/ s3://aucctus-react --cache-control 'public,max-age=31536000,immutable'
      # overwrite index file with correct TTLs so latest changes are reflected immediately
      - name: Deploy index to S3
        run: aws s3 cp ./build/index.html s3://aucctus-react --cache-control 'public,max-age=60'
